spring.application.name=savingAccount

## MySQL DATASOURCE
spring.datasource.url=jdbc:mysql://localhost:3306/saving_account?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

## Hibernate Properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=6jZ9FwXp7yK2vM5Nq8rUuXwZ3b6e9h1k4m7pStVwYz0=
jwt.expiration=604800000
	
# expiration = 24 hours in milliseconds (86400000)
# secret must be at least 32 characters for HS256
